### PR TITLE
Update to 0.7.0, add traversaro as mantainers and use ninja on Windows

### PR DESCRIPTION
**Pull request by traversaro**
Version of https://github.com/conda-forge/fcl-feedstock/pull/9 updated removing the patches as they were accepted upstream in https://github.com/flexible-collision-library/fcl/pull/530 . Furthermore, switch arm64 and ppc64 to use cross-compilation as otherwise build in emulation is quite slow.
Adding myself as mantainer in the repo as currently @wolfv is the only mantainer.
I also switched to use Ninja on Windows to speed up a bit the build.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Windows fails with:
~~~
[ 73%] Building CXX object test/CMakeFiles/test_fcl_collision.dir/test_fcl_collision.cpp.obj
cl : Command line warning D9025 : overriding '/W3' with '/W1'
test_fcl_collision.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits(1291): note: see reference to class template instantiation 'std::_Aligned<592,16,double,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits(1298): note: see reference to class template instantiation 'std::_Aligned<592,16,int,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits(1305): note: see reference to class template instantiation 'std::_Aligned<592,16,short,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits(1312): note: see reference to class template instantiation 'std::_Aligned<592,16,char,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits(1320): note: see reference to class template instantiation 'std::aligned_storage<592,16>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits(1352): note: see reference to alias template instantiation 'std::aligned_storage_t<592,16>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits(1357): note: see reference to class template instantiation 'std::aligned_union<1,_Ty>' being compiled
~~~

**Comment by traversaro** [comment]
> Windows fails with:

This error is similar to https://github.com/conda-forge/rbdl-feedstock/pull/27 and https://github.com/conda-forge/libignition-physics-feedstock/pull/12#issuecomment-808708991 . In ign-physics, we defined that symbol in a VS2017-specific patch: https://github.com/conda-forge/libignition-physics-feedstock/blob/a3500e5ea3fb81049074fd41f6aa600173da7ff3/recipe/vs2017_support.patch .

**Comment by traversaro** [comment]
New CI failure:
~~~
2021-11-13T13:49:02.4680274Z [170/200] Building CXX object test\geometry\shape\CMakeFiles\test_convex.dir\test_convex.cpp.obj
2021-11-13T13:49:02.4681650Z FAILED: test/geometry/shape/CMakeFiles/test_convex.dir/test_convex.cpp.obj 
2021-11-13T13:49:02.4701118Z C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DGTEST_DONT_DEFINE_ASSERT_EQ=1 -DGTEST_DONT_DEFINE_ASSERT_GE=1 -DGTEST_DONT_DEFINE_ASSERT_GT=1 -DGTEST_DONT_DEFINE_ASSERT_LE=1 -DGTEST_DONT_DEFINE_ASSERT_LT=1 -DGTEST_DONT_DEFINE_ASSERT_NE=1 -DGTEST_DONT_DEFINE_FAIL=1 -DGTEST_DONT_DEFINE_SUCCEED=1 -DGTEST_DONT_DEFINE_TEST=1 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -I%SRC_DIR%\test -I%SRC_DIR%\test\gtest -I%SRC_DIR%\test\gtest\include -I%SRC_DIR%\build\include -I%SRC_DIR%\include -I%SRC_DIR%\test\. -I%SRC_DIR%\build\test -I%PREFIX%\Library\include -I%PREFIX%\Library\include\eigen3 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /EHsc /MP /W1 /bigobj /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fotest\geometry\shape\CMakeFiles\test_convex.dir\test_convex.cpp.obj /Fdtest\geometry\shape\CMakeFiles\test_convex.dir\ /FS -c %SRC_DIR%\test\geometry\shape\test_convex.cpp
2021-11-13T13:49:02.4708239Z cl : Command line warning D9025 : overriding '/W3' with '/W1'
2021-11-13T13:49:02.4715376Z %SRC_DIR%\test\geometry\shape\test_convex.cpp(780): error C2065: 'M_PI': undeclared identifier
2021-11-13T13:49:02.4723690Z %SRC_DIR%\test\geometry\shape\test_convex.cpp(780): error C2789: 'dphi': an object of const-qualified type must be initialized
2021-11-13T13:49:02.4724754Z %SRC_DIR%\test\geometry\shape\test_convex.cpp(780): note: see declaration of 'dphi'
2021-11-13T13:49:02.4725572Z %SRC_DIR%\test\geometry\shape\test_convex.cpp(793): error C2065: 'M_PI': undeclared identifier
2021-11-13T13:49:02.4726728Z %SRC_DIR%\test\geometry\shape\test_convex.cpp(793): error C2789: 'dtheta': an object of const-qualified type must be initialized
2021-11-13T13:49:02.4727578Z %SRC_DIR%\test\geometry\shape\test_convex.cpp(793): note: see declaration of 'dtheta'
~~~

Fix proposed upstream in https://github.com/flexible-collision-library/fcl/pull/553 and backported in this PR.

**Comment by traversaro** [comment]
Windows fails with:
~~~
[177/200] Building CXX object test\geometry\shape\CMakeFiles\test_convex.dir\test_convex.cpp.obj
FAILED: test/geometry/shape/CMakeFiles/test_convex.dir/test_convex.cpp.obj 
C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DGTEST_DONT_DEFINE_ASSERT_EQ=1 -DGTEST_DONT_DEFINE_ASSERT_GE=1 -DGTEST_DONT_DEFINE_ASSERT_GT=1 -DGTEST_DONT_DEFINE_ASSERT_LE=1 -DGTEST_DONT_DEFINE_ASSERT_LT=1 -DGTEST_DONT_DEFINE_ASSERT_NE=1 -DGTEST_DONT_DEFINE_FAIL=1 -DGTEST_DONT_DEFINE_SUCCEED=1 -DGTEST_DONT_DEFINE_TEST=1 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -I%SRC_DIR%\test -I%SRC_DIR%\test\gtest -I%SRC_DIR%\test\gtest\include -I%SRC_DIR%\build\include -I%SRC_DIR%\include -I%SRC_DIR%\test\. -I%SRC_DIR%\build\test -I%PREFIX%\Library\include -I%PREFIX%\Library\include\eigen3 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /EHsc /MP /W1 /bigobj /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fotest\geometry\shape\CMakeFiles\test_convex.dir\test_convex.cpp.obj /Fdtest\geometry\shape\CMakeFiles\test_convex.dir\ /FS -c %SRC_DIR%\test\geometry\shape\test_convex.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W1'
d:\bld\fcl_1636813126473\work\test\eigen_matrix_compare.h(66) : fatal error C1002: compiler is out of heap space in pass 2
[178/200] Building CXX object test\narrowphase\detail\CMakeFiles\test_collision_func_matrix.dir\test_collision_func_matrix.cpp.obj
FAILED: test/narrowphase/detail/CMakeFiles/test_collision_func_matrix.dir/test_collision_func_matrix.cpp.obj 
C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DGTEST_DONT_DEFINE_ASSERT_EQ=1 -DGTEST_DONT_DEFINE_ASSERT_GE=1 -DGTEST_DONT_DEFINE_ASSERT_GT=1 -DGTEST_DONT_DEFINE_ASSERT_LE=1 -DGTEST_DONT_DEFINE_ASSERT_LT=1 -DGTEST_DONT_DEFINE_ASSERT_NE=1 -DGTEST_DONT_DEFINE_FAIL=1 -DGTEST_DONT_DEFINE_SUCCEED=1 -DGTEST_DONT_DEFINE_TEST=1 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -I%SRC_DIR%\test -I%SRC_DIR%\test\gtest -I%SRC_DIR%\test\gtest\include -I%SRC_DIR%\build\include -I%SRC_DIR%\include -I%SRC_DIR%\test\. -I%SRC_DIR%\build\test -I%PREFIX%\Library\include -I%PREFIX%\Library\include\eigen3 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /EHsc /MP /W1 /bigobj /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fotest\narrowphase\detail\CMakeFiles\test_collision_func_matrix.dir\test_collision_func_matrix.cpp.obj /Fdtest\narrowphase\detail\CMakeFiles\test_collision_func_matrix.dir\ /FS -c %SRC_DIR%\test\narrowphase\detail\test_collision_func_matrix.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W1'
d:\bld\fcl_1636813126473\_h_env\library\include\eigen3\eigen\src/Core/Block.h(110): fatal error C1060: compiler is out of heap space
[179/200] Building CXX object test\CMakeFiles\test_fcl_sphere_cylinder.dir\test_fcl_sphere_cylinder.cpp.obj
cl : Command line warning D9025 : overriding '/W3' with '/W1'
~~~

Better to go back to use NMake so we do not have parallel builds.

**Comment by wolfv** [comment]
Thanks awesome!

**Comment by traversaro** [comment]
> Thanks awesome!

Thanks for merging!

**Pull request merged**
